Registrar/Models/Course.cs
using System.Collections.Generic;

namespace Registrar.Models
{
  public class Course
  {
    public int CourseId {get; set;}
    public string Name {get; set;}
    public List<Student> Students {get; set;}
  }
}

Registrar/Models/RegistrarContext.cs
using Microsoft.EntityFrameworkCore;

namespace Registrar.Models
{
  public class RegistrarContext : DbContext
  {

    public DbSet<Student> Students { get; set; }
    public DbSet<Course> Courses { get; set; }

    public RegistrarContext(DbContextOptions options) : base(options) { }
  }
}

Registrar/Models/Student.cs
namespace Registrar.Models
{
  public class Student
  {
    public string StudentName {get; set;}
    public int StudentId {get; set;}
    public int CourseId {get; set;}
    public Course Course { get; set; }
  }
}

Registrar/Controllers/CoursesController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Registrar.Models;
using System.Collections.Generic;
using System.Linq;

namespace Registrar.Controllers
{
  public class CoursesController : Controller
  {
    private readonly RegistrarContext _db;

    public CoursesController(RegistrarContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Course> model = _db.Courses.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create (Course course)
    {
      _db.Courses.Add(course);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Course thisCourse = _db.Courses
                              .Include(course => course.Students)
                              .FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }
    public ActionResult Delete(int id)
    {
      Course thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Course thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
      _db.Courses.Remove(thisCourse);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    }
  }

Registrar/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Registrar.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }

    }
}

Registrar/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Registrar.Models;
using System.Collections.Generic;
using System.Linq;

namespace Registrar.Controllers
{
  public class StudentsController : Controller
  {
    private readonly RegistrarContext _db;

    public StudentsController(RegistrarContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Student> model = _db.Students
                            .Include(student => student.Course)
                            .ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Student student)
    {
      _db.Students.Add(student);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      Student thisStudent = _db.Students
                              .Include(student => student.Course)
                              .FirstOrDefault(student => student.StudentId == id);
      return View(thisStudent);
    }

    public ActionResult Delete(int id)
    {
      Student thisStudent = _db.Students.FirstOrDefault(student => student.StudentId == id);
      return View(thisStudent);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Student thisStudent = _db.Students.FirstOrDefault(student => student.StudentId == id);
      _db.Students.Remove(thisStudent);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Registrar/Views/Courses/Create.cshtml
@model Registrar.Models.Course

<h4>Add a new course</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  <input type="submit" value="Add new course"/>
}

Registrar/Views/Courses/Delete.cshtml
@model Registrar.Models.Course

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

Registrar/Views/Courses/Details.cshtml
@model Registrar.Models.Course;
@using Registrar.Models;
@using System.Collections.Generic;

<h2>Courses Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>

  <h3>Students:</h3>
  <ul>
    @foreach (Student student in Model.Students)
    {
      <li>@Html.ActionLink($"{student.StudentName}", "Details", "Students", new { id = student.StudentId })</li>
    }
  </ul>



<p>@Html.ActionLink("Delete Course", "Delete", new { id = Model.CourseId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

Registrar/Views/Courses/Index.cshtml
@using Registrar.Models;

<h1> Courses </h1>

<p>@Html.ActionLink("Create a course", "Create")</p>

<ul>
  @foreach (Course course in Model)
  {
    <li> @Html.ActionLink($"{course.Name}", "Details", new { id = course.CourseId})</li>
  }
</ul>

Registrar/Views/Home/Index.cshtml
<h1>Welcome to the UW Registrar!</h1>
<p>@Html.ActionLink("Click to see all students", "Index", "Students")</p>
<p>@Html.ActionLink("Click to see all courses", "Index", "Courses")</p>

Registrar/Views/Student/Create.cshtml
@model Registrar.Models.Student

<h4>Add a new student</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.StudentName)
  @Html.TextBoxFor(model => model.StudentName)

  <input type="submit" value="Add new student"/>
}

Registrar/Views/Students/Create.cshtml
@model Registrar.Models.Student

<h4>Add a new student</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.StudentName)
  @Html.TextBoxFor(model => model.StudentName)

  @Html.LabelFor(model => model.Course)
  @Html.DropDownList("CourseId")

  <input type="submit" value="Add new student"/>
}

Registrar/Views/Students/Delete.cshtml
@model Registrar.Models.Student

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.StudentName): @Html.DisplayFor(model => model.StudentName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

Registrar/Views/Students/Details.cshtml
@model Registrar.Models.Student

<h2>Student Details</h2>
<h3>@Html.DisplayFor(model => model.StudentName)</h3>
<h2>Classes</h2>
<br>
<h3>@Html.DisplayFor(model => model.Course.Name)</h3>

<p>@Html.ActionLink("Delete Student", "Delete", new { id = Model.StudentId })</p>

Registrar/Views/Students/Index.cshtml
@using Registrar.Models;

<h1>Students</h1>

@if (@Model.Count == 0)
{
  <h3>No students have been added yet!</h3>
} 
else
{
  <ul>
    @foreach (Student student in Model)
    {
      <li>@Html.ActionLink($"{student.StudentName}", "Details", new { id = student.StudentId })</li>
    }
  </ul>
}

<p>@Html.ActionLink("Click to Add a Student", "Create", "Students")</p>